# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-20 00:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_remove_automobiles_make'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automobiles',
            name='created_at',
        ),
        migrations.AddField(
            model_name='automobiles',
            name='Founder',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
